<?php

return [
    'singular' => 'Payment',
    'plural'   => 'Payments',
    'record'   => 'payment',
    'records'  => 'payments',
    'new'      => 'Record payment',

    'index_title'    => 'Payments',
    'index_subtitle' => 'Payments applied to invoices.',
    'show_title'     => 'Payment — Details',
    'create_title'   => 'Record payment',
    'edit_title'     => 'Edit payment',
    'delete_title'   => 'Delete payment',
    'trash_title'    => 'Payments trash',

    // Legacy keys that other generated screens (Delete/Trash/EditAll) still reference.
    'name'          => 'Reference',
    'is_active'     => 'Status',
    'filter_name'   => 'Reference',
    'name_unique'   => 'This reference already exists.',

    'reference'    => 'Reference',
    'reference_hint' => 'Short internal code to identify the payment. Useful for accounting reconciliation.',
    'filter_reference' => 'Reference',
    'company'      => 'Customer',
    'invoice'      => 'Invoice',
    'invoice_hint' => 'Invoice the payment is applied to. Leave empty for an advance or customer credit.',
    'invoice_number' => 'Invoice #',
    'type'         => 'Type',
    'type_hint'    => 'Invoice payment = clears a balance; Deposit = advance with no invoice; Credit memo = refund credit; Refund = reverse collection.',
    'payment_method' => 'Method',
    'payment_method_hint' => 'Collection method: transfer, card, cash, check. Determines if a bank reference is required.',
    'amount'       => 'Amount',
    'amount_hint'  => 'Amount actually received. If it exceeds the invoice balance, the excess remains as customer credit.',
    'currency'     => 'Currency',
    'currency_hint' => 'Currency the payment was received in. Must match the invoice currency to apply the balance.',
    'paid_at'      => 'Payment date',
    'paid_at_hint' => 'Date and time the payment was credited to the account. Shown on the receipt and cash reports.',
    'reconciled_at'=> 'Reconciled',
    'status'       => 'Status',
    'status_hint'  => 'Pending = unconfirmed; Completed = applied to balance; Failed = rejected by the bank.',
    'bank_reference' => 'Bank reference',
    'bank_reference_hint' => 'Bank operation number, transfer code, or check number. Useful for reconciliation.',
    'external_transaction_id' => 'External transaction ID',
    'external_transaction_id_hint' => 'ID generated by the payment gateway (Stripe, MercadoPago, PayPal). Enables traceability and disputes.',
    'notes'        => 'Notes',
    'notes_hint'   => 'Internal notes about the payment: special conditions, customer remarks, treasury instructions.',
    'required_suffix' => 'required',

    'edit_hint'    => 'Edit this payment',
    'delete_hint'  => 'Delete (moves to trash)',
    'restore_hint' => 'Will return to the main listing.',

    'empty_hint' => 'No payments yet.',

    'type_options' => [
        'invoice_payment' => 'Invoice payment',
        'deposit'         => 'Deposit / Advance',
        'credit_memo'     => 'Credit memo',
        'refund'          => 'Refund',
    ],

    'status_options' => [
        'pending'   => 'Pending',
        'completed' => 'Completed',
        'failed'    => 'Failed',
        'refunded'  => 'Refunded',
        'disputed'  => 'Disputed',
    ],

    // Flash messages
    'created' => 'Payment recorded.',
    'saved'   => 'Payment updated.',
    'deleted' => 'Payment deleted.',

    // Validation
    'reference_unique'    => 'A payment with this reference already exists in the workspace.',
    'items_required'      => 'Add at least one line to the payment.',
    'is_active_required'  => 'Active status is required.',

    // Delete confirmation
    'delete_about' => 'You are about to delete the payment ":name". It will go to the trash.',
    'deleted_description_required' => 'Provide a reason for the deletion.',
    'deleted_description_min'      => 'Reason must be at least 3 characters.',
    'deleted_description_max'      => 'Reason cannot exceed 1000 characters.',

    // Bulk
    'bulk_set_active' => 'Change active status',

    // Export
    'export_filename'           => 'payments_export',
    'import_template_filename'  => 'payments-template.xlsx',
    'export_title'              => 'Payments Report',
    'export_limit_exceeded'     => 'The :format export exceeds the limit (:count rows vs :limit max). Use CSV for large datasets.',
    'export_format_limit_hint'  => 'Max :limit rows for this format. Use CSV for large datasets.',
    'export_no_limit_hint'      => 'No limit — recommended for large datasets.',

    // Edit All
    'edit_all_title'      => 'Payments — Edit All',
    'edit_all_subtitle'   => 'Edit reference and status of many payments at once. Click "Save all" to confirm.',
    'edit_all_changes'    => '{0} No changes|{1} 1 pending change|[2,*] :count pending changes',
    'edit_all_save_all'   => 'Save all',
    'edit_all_discard'    => 'Discard changes',
    'edit_all_no_results' => 'No payments match the filter.',

    'table_headers' => [
        'editable_name'   => 'Reference (editable)',
        'editable_status' => 'Status (editable)',
    ],

    // Onboarding tour
    'tour' => [
        'step1_title' => 'Welcome to Payments',
        'step1_body'  => 'This is your payments module. Key features in under a minute.',
        'step2_title' => 'Filters',
        'step2_body'  => 'Search and filter by reference, status, type, method, dates and amount. Active filters show as chips above the table.',
        'step3_title' => 'Saved views',
        'step3_body'  => 'Save your favorite combo of filters, columns and sort, then apply with one click. Each user has their own.',
        'step4_title' => 'Columns',
        'step4_body'  => 'Show or hide columns and your choice is remembered. Required columns cannot be hidden.',
        'step5_title' => 'Export & import',
        'step5_body'  => 'Export to Excel, PDF or Word in the background — you will be notified when ready. Import from Excel or CSV with preview before confirming.',
        'step6_title' => 'Edit many at once',
        'step6_body'  => '"Edit all" lets you modify many payments together. All changes are confirmed in a single save.',
        'step7_title' => 'Favorites',
        'step7_body'  => 'The star marks a payment as favorite. Favorites always appear at the top and each user has their own.',
        'step8_title' => 'Bulk operations',
        'step8_body'  => 'Select rows with the checkboxes — a bar appears to delete or restore. Works with hundreds of rows; large batches run in the background.',
    ],
];
